# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Medellin iOS Blog
email: comunidadmedellinios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog para informarte de los pasados Meetup de la comunidad Medellin iOS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://MedelliniOS.github.io" # the base hostname & protocol for your site
twitter_username: MedelliniOS
github_username:  MedelliniOS

# Build settings
markdown: kramdown
